# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_KEY: '1720486554633812'  #Note the use of the single quotes ' ' here. 
FACEBOOK_APP_SECRET: '669146b43e1c3ee63173fae5afc8011f' 

AWSAccessKeyId: 'AKIAJMIIGFTUDWJNPCTQ'
AWSSecretKey: '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'
AWSDirectory: 'sivaairbnbclone'

#for payment
BRAINTREE_MERCHANT_ID: 'brmsynd6tssz6sqm'
BRAINTREE_PUBLIC_KEY: '9qjcnwpwv55wtrsx'
BRAINTREE_PRIVATE_KEY: 'f79a2ffd5971f266f7bbe4940cdf4f06'


# gmail_username: 'username@gmail.com'
# gmail_password: 'Gmail password'

